### PR TITLE
Progress messages

### PR DESCRIPTION
**Pull request by jeanparpaillon**
If this lib is still used, a bunch of improvements / fixes

### CODE REVIEW

**Comment by fhunleth** [comment]
I don't use it, but I'm happy to merge your PRs. I assume that you'll want a release. Would you mind me making you a maintainer?

**Comment by jeanparpaillon** [comment]
@fhunleth hi, ok to be a maintainer
btw, is there a 'recommended' lib for building firmware upgrades ? There are many of them

**Comment by fhunleth** [comment]
For `ssh` updates, we've only using https://github.com/nerves-project/nerves_ssh/ which uses https://github.com/nerves-project/ssh_subsystem_fwup. That's the only core Nerves firmware update project. 

I see now that `nerves_firmware_ssh` isn't in the attic. Let me double check one thing and put it there, since we haven't maintained that project 1.5 years. We totally neglected putting notes on that project. I'm so sorry for that confusion. The big change from `nerves_firmware_ssh` -> `ssh_subsystem_fwup` is to avoid creating the `ssh` server. This provides a lot more flexibility with how Erlang's ssh server is configured and makes it so that the update code doesn't have to deal with authentication.

**Comment by jeanparpaillon** [comment]
@fhunleth thanks for the update.

**Pull request merged**
